<?php
$today = date( 'Y-m-d' );
$yesterday = getDateWithOffset( -1 );
$tenDaysAgo = getDateWithOffset( -10 );
$elevenDaysAgo = getDateWithOffset( -11 );
$twentyDaysAgo = getDateWithOffset( -20 );
$twentyOneDaysAgo = getDateWithOffset( -21 );
$thirtyDaysAgo = getDateWithOffset( -30 );
$thirtyOneDaysAgo = getDateWithOffset( -31 );
$sixtyDaysAgo = getDateWithOffset( -60 );
$sixtyOneDaysAgo = getDateWithOffset( -61 );
$nintyDaysAgo = getDateWithOffset( -90 );
$nintyOneDaysAgo = getDateWithOffset( -91 );
$RedZone = getDateWithOffset( -9000 );

?>
<ul class="nav nav-tabs">
  <!--  <li title="From <?php echo $date; ?> To <?php echo $date; ?>" class=" nav-link <?php echo $_REQUEST['tab']=='Todays Fresh Tasks' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&start_date=<?php echo $date; ?>&end_date=<?php echo $date; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=Todays Fresh Tasks">Today's Fresh Tasks</a></li>-->
  
  <li  title="From <?php echo $date; ?> To <?php echo $date; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='Fresh Inquiries' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&start_date=<?php echo $date; ?>&end_date=<?php echo $date; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=Fresh Inquiries">Fresh Inquiries (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$date' AND '$date' ") ?>)</a></li>
    
  <li  title="From <?php echo $yesterday; ?> To <?php echo $tenDaysAgo; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='2-10 Days' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $tenDaysAgo ?>&end_date=<?php echo $yesterday; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=2-10 Days">2-10 Days (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$tenDaysAgo' AND '$yesterday' ") ?>)</a></li>
    
  <li  title="From <?php echo $elevenDaysAgo; ?> To <?php echo $twentyDaysAgo; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='11-20 Days' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $twentyDaysAgo ?>&end_date=<?php echo $elevenDaysAgo; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=11-20 Days">11-20 Days (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$twentyDaysAgo' AND '$elevenDaysAgo' ") ?>)</a></li>
    
  <li  title="From <?php echo $twentyOneDaysAgo; ?> To <?php echo $thirtyDaysAgo; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='21-30 Days' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $thirtyDaysAgo ?>&end_date=<?php echo $twentyOneDaysAgo; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=21-30 Days">21-30 Days (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$thirtyDaysAgo' AND  '$twentyOneDaysAgo'") ?>)</a></li>
    
  <li  title="From <?php echo $thirtyOneDaysAgo; ?> To <?php echo $sixtyDaysAgo; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='31-60 Days' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $sixtyDaysAgo; ?>&end_date=<?php echo $thirtyOneDaysAgo; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=31-60 Days">31-60 Days (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$sixtyDaysAgo' AND '$thirtyOneDaysAgo' ") ?>)</a></li>
    
  <li  title="From <?php echo $sixtyOneDaysAgo; ?> To <?php echo $nintyDaysAgo; ?>"  class=" nav-link <?php echo $_REQUEST['tab']=='60-90 Days' ? 'active' : '' ?>"><a href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $nintyDaysAgo; ?>&end_date=<?php echo $sixtyOneDaysAgo; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=60-90 Days">61-90 Days (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$nintyOneDaysAgo' AND '$sixtyOneDaysAgo' ") ?>)</a></li>
  
 
  <li  title="From <?php echo $date; ?> To <?php echo $date; ?>"   class="nav-link"><a class="text-info" href="view_inquiry.php?date_type=date%28recall_date%29&start_date=<?php echo $date; ?>&end_date=<?php echo $date; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=<?php echo $recalls; ?>&seller=<?php echo $login_user ?>">Recalls Today (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND date(recall_date) BETWEEN '$date' AND '$date' ") ?>)</a></li>
  <li  class="nav-link"><a class="text-black-50" href="view_inquiry.php?limit=50&date_type=date%28allocated_at%29">All Inquiries</a></li>
 
    <li  title="From <?php echo $nintyOneDaysAgo; ?> To <?php echo $RedZone; ?>"  class=" bg-danger nav-link <?php echo $_REQUEST['tab']=='Red Zone' ? 'active' : '' ?>"><a class="text-light" href="view_inquiry.php?date_type=date%28allocated_at%29&&start_date=<?php echo $RedZone; ?>&end_date=<?php echo $nintyOneDaysAgo; ?>&order_status=order_status&call_status=call_status&gender=gender&phone1network=phone1network&phone2network=phone2network&disease=disease&source=source&record_type=Inquiry&age=age&committed_amount=committed_amount&province=province&district=district&tehsil=tehsil&limit=50&seller=<?php echo $login_user ?>&tab=Red Zone">Red Zone (<?php echo showQuery("SELECT COUNT(*) FROM `inquiry` WHERE allocated_to='$login_user' AND record_type='Inquiry' AND date(allocated_at) BETWEEN '$RedZone' AND '$nintyOneDaysAgo' ") ?>)</a></li>
</ul>
